"""add lines.start_seconds for LRC timestamps

Revision ID: 32d6cf736a5d
Revises: 8adfcb7065b6
Create Date: 2026-05-01 18:21:28.040805

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d6cf736a5d'
down_revision: str | None = '8adfcb7065b6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lines', sa.Column('start_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lines', 'start_seconds')
    # ### end Alembic commands ###
