"""initial schema

Revision ID: 4977bbd8b9a9
Revises: 
Create Date: 2026-05-01 11:51:52.367756

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4977bbd8b9a9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # --- Extensiones y configuración FTS en español (manual, no autogen) ---
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    # Config FTS 'es_unaccent' = español + stripping de acentos.
    # Necesario porque las letras de Robe usan tilde de forma poética
    # ("se acabó" vs "se acabo") y queremos que el FTS las trate igual.
    op.execute("DROP TEXT SEARCH CONFIGURATION IF EXISTS es_unaccent")
    op.execute("CREATE TEXT SEARCH CONFIGURATION es_unaccent (COPY = spanish)")
    op.execute(
        "ALTER TEXT SEARCH CONFIGURATION es_unaccent "
        "ALTER MAPPING FOR hword, hword_part, word "
        "WITH unaccent, spanish_stem"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('active_years', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('interpretation_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_raw', sa.Text(), nullable=True),
    sa.Column('content_clean', sa.Text(), nullable=True),
    sa.Column('referenced_song_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'url', name='uq_interp_sources_kind_url')
    )
    op.create_index('ix_interp_sources_kind', 'interpretation_sources', ['kind'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('track_count', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id', 'slug', name='uq_albums_artist_slug')
    )
    op.create_index('ix_albums_artist_year', 'albums', ['artist_id', 'year'], unique=False)
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('lyrics_raw', sa.Text(), nullable=True),
    sa.Column('lyrics_clean', sa.Text(), nullable=True),
    sa.Column('lyrics_clean_tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('genius_id', sa.Integer(), nullable=True),
    sa.Column('genius_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('album_id', 'slug', name='uq_songs_album_slug')
    )
    op.create_index('ix_songs_genius_id', 'songs', ['genius_id'], unique=True)
    op.create_index('ix_songs_lyrics_clean_tsv', 'songs', ['lyrics_clean_tsv'], unique=False, postgresql_using='gin')
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('start_line_index', sa.Integer(), nullable=False),
    sa.Column('end_line_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.CheckConstraint('end_line_index >= start_line_index', name='ck_chunks_index_order'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_id', 'start_line_index', name='uq_chunks_song_start')
    )
    op.create_index(op.f('ix_chunks_song_id'), 'chunks', ['song_id'], unique=False)
    op.create_table('lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('line_index', sa.Integer(), nullable=False),
    sa.Column('stanza_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_tsv', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_id', 'line_index', name='uq_lines_song_index')
    )
    op.create_index(op.f('ix_lines_song_id'), 'lines', ['song_id'], unique=False)
    op.create_index('ix_lines_text_trgm', 'lines', ['text'], unique=False, postgresql_using='gin', postgresql_ops={'text': 'gin_trgm_ops'})
    op.create_index('ix_lines_text_tsv', 'lines', ['text_tsv'], unique=False, postgresql_using='gin')

    # --- Triggers para mantener tsvector al día (manual, no autogen) ---
    op.execute("""
        CREATE OR REPLACE FUNCTION lines_tsv_trigger() RETURNS trigger AS $$
        BEGIN
          NEW.text_tsv := to_tsvector('es_unaccent', coalesce(NEW.text, ''));
          RETURN NEW;
        END
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER lines_tsv_update
          BEFORE INSERT OR UPDATE OF text ON lines
          FOR EACH ROW EXECUTE FUNCTION lines_tsv_trigger()
    """)
    op.execute("""
        CREATE OR REPLACE FUNCTION songs_lyrics_tsv_trigger() RETURNS trigger AS $$
        BEGIN
          NEW.lyrics_clean_tsv := to_tsvector('es_unaccent', coalesce(NEW.lyrics_clean, ''));
          RETURN NEW;
        END
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER songs_lyrics_tsv_update
          BEFORE INSERT OR UPDATE OF lyrics_clean ON songs
          FOR EACH ROW EXECUTE FUNCTION songs_lyrics_tsv_trigger()
    """)

    op.create_table('song_interpretations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('source_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('distilled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidence IN ('high', 'medium', 'low')", name='ck_song_interpretations_confidence'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Triggers + funciones (manual, no autogen)
    op.execute("DROP TRIGGER IF EXISTS songs_lyrics_tsv_update ON songs")
    op.execute("DROP FUNCTION IF EXISTS songs_lyrics_tsv_trigger()")
    op.execute("DROP TRIGGER IF EXISTS lines_tsv_update ON lines")
    op.execute("DROP FUNCTION IF EXISTS lines_tsv_trigger()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_interpretations')
    op.drop_index('ix_lines_text_tsv', table_name='lines', postgresql_using='gin')
    op.drop_index('ix_lines_text_trgm', table_name='lines', postgresql_using='gin', postgresql_ops={'text': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_lines_song_id'), table_name='lines')
    op.drop_table('lines')
    op.drop_index(op.f('ix_chunks_song_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('ix_songs_lyrics_clean_tsv', table_name='songs', postgresql_using='gin')
    op.drop_index('ix_songs_genius_id', table_name='songs')
    op.drop_table('songs')
    op.drop_index('ix_albums_artist_year', table_name='albums')
    op.drop_table('albums')
    op.drop_table('users')
    op.drop_index('ix_interp_sources_kind', table_name='interpretation_sources')
    op.drop_table('interpretation_sources')
    op.drop_table('artists')
    # ### end Alembic commands ###

    # Config FTS personalizada (manual)
    op.execute("DROP TEXT SEARCH CONFIGURATION IF EXISTS es_unaccent")
    # Las extensiones se dejan instaladas (otros usuarios de la BD podrían
    # depender de ellas). No las droppeamos en downgrade.
