"""seo_content table

Revision ID: 567cb06d73eb
Revises: cf889329a32a
Create Date: 2026-05-02 20:49:44.174402

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '567cb06d73eb'
down_revision: str | None = 'cf889329a32a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seo_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('meta_title', sa.String(length=256), nullable=True),
    sa.Column('meta_description', sa.String(length=512), nullable=True),
    sa.Column('schema_jsonld', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_by', sa.String(length=32), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_seo_content_entity')
    )
    op.create_index('ix_seo_content_published', 'seo_content', ['published'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_seo_content_published', table_name='seo_content')
    op.drop_table('seo_content')
    # ### end Alembic commands ###
