"""add youtube_id to songs

Revision ID: 8adfcb7065b6
Revises: 4977bbd8b9a9
Create Date: 2026-05-01 18:06:58.144938

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8adfcb7065b6'
down_revision: str | None = '4977bbd8b9a9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('youtube_id', sa.String(length=32), nullable=True))
    op.add_column('songs', sa.Column('youtube_match_quality', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'youtube_match_quality')
    op.drop_column('songs', 'youtube_id')
    # ### end Alembic commands ###
