"""interpretation_sources.for_seo_only

Revision ID: cf889329a32a
Revises: 96d396b840e5
Create Date: 2026-05-02 20:14:59.418310

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf889329a32a'
down_revision: str | None = '96d396b840e5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        'interpretation_sources',
        sa.Column('for_seo_only', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('interpretation_sources', 'for_seo_only', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interpretation_sources', 'for_seo_only')
    # ### end Alembic commands ###
